'use client'
import { useState, useEffect, useRef } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '../../lib/supabase'
import Navbar from '../../components/Navbar'
import { useToast } from '../../components/Toast'
import { Upload, Check, AlertCircle, Trash2, ChevronLeft, Calendar, FileText } from 'lucide-react'

export default function AttendanceImportPage() {
  const router = useRouter()
  const { addToast } = useToast()
  const fileInputRef = useRef(null)

  const [month, setMonth] = useState(new Date().getMonth() + 1)
  const [year, setYear] = useState(new Date().getFullYear())
  const [loading, setLoading] = useState(false)
  const [staff, setStaff] = useState([])
  const [parsedData, setParsedData] = useState([])
  const [matchedRecords, setMatchedRecords] = useState([])
  const [isDragging, setIsDragging] = useState(false)

  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ]

  const nameAliases = {
    'shahdat': 'shahadat',
    'rabiul': 'robiul',
    'alam noor': 'alam nur',
    'esha': 'esa',
    'ajoy': 'ajoy'
  }

  useEffect(() => {
    const token = localStorage.getItem('cc_token')
    const role = localStorage.getItem('cc_role')
    if (!token || role !== 'admin') {
      router.replace('/')
      return
    }
    fetchStaff()
  }, [router])

  async function fetchStaff() {
    const { data } = await supabase.from('staff').select('id, name').eq('is_active', true).order('name')
    setStaff(data || [])
  }

  function parseDays(val) {
    if (!val || val === '--') return 0
    // "24 Days" or "23 Days | 96 h"
    const match = val.match(/^(\d+)/)
    return match ? parseInt(match[1]) : 0
  }

  function normalizeName(name) {
    if (!name) return ''
    let n = name.toLowerCase().trim()
    for (const [key, val] of Object.entries(nameAliases)) {
      if (n === key) return val
    }
    return n
  }

  function findBestMatch(rysenovaName) {
    if (!rysenovaName) return null
    const normalized = normalizeName(rysenovaName)
    
    // Direct match
    let match = staff.find(s => normalizeName(s.name) === normalized)
    if (match) return match.id

    // Partial match (if Rysenova name is contained in staff name or vice versa)
    match = staff.find(s => {
      const sName = normalizeName(s.name)
      return sName.includes(normalized) || normalized.includes(sName)
    })
    if (match) return match.id

    // Alias match
    for (const [alias, target] of Object.entries(nameAliases)) {
        if (normalized.includes(alias)) {
            match = staff.find(s => normalizeName(s.name).includes(target))
            if (match) return match.id
        }
    }

    return null
  }

  const handleFileUpload = (e) => {
    const file = e.target.files[0]
    if (!file) return
    processFile(file)
  }

  const processFile = (file) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target.result
      const rows = text.split(/\r?\n/).map(row => {
        return row.split(',').map(cell => cell.replace(/^"(.*)"$/, '$1').trim())
      })

      const header = rows[3] || []
      const nameIdx = header.findIndex(h => h.toLowerCase().includes('name') || h.toLowerCase().includes('employee'))
      const checkInIdx = header.findIndex(h => h.toLowerCase().includes('check-in') || h.toLowerCase().includes('in time'))
      
      // If we can't find columns by name, fall back to indices
      const finalNameIdx = nameIdx !== -1 ? nameIdx : 0
      const finalCheckInIdx = checkInIdx !== -1 ? checkInIdx : 3 // Assuming 3 if not found

      const dataRows = rows.slice(4)
      const aggregation = {}

      for (const row of dataRows) {
        if (row.length < 2) continue
        const name = row[finalNameIdx]
        if (!name || name === 'Generated by Rysenova' || name.toLowerCase().includes('employee') || name.toLowerCase().includes('total')) continue
        
        if (!aggregation[name]) {
          aggregation[name] = { present: 0, absent: 0, late: 0 }
        }

        // Determine if this is a summary row or a daily row
        // Summary rows have "24 Days" style strings in column 4
        const col4 = row[4] || ''
        const isSummary = col4.toLowerCase().includes('day')
        
        if (isSummary) {
          // If it's a summary row, we still take present/absent from columns
          // but user said "do not check the late_days column ... just check the check in column"
          // However, a summary row DOES NOT HAVE a check-in time.
          // This implies the user is now providing DAILY logs.
          aggregation[name].present = parseDays(row[4])
          aggregation[name].absent = parseDays(row[5])
          // We can't calculate late from a summary row's check-in column (doesn't exist)
          // So we'll skip late calculation here or use the column if it's there
        } else {
          // Daily row logic
          aggregation[name].present += 1
          
          const timeStr = row[finalCheckInIdx]
          if (timeStr && timeStr !== '--') {
            const timeMatch = timeStr.match(/(\d{1,2}):(\d{2})/)
            if (timeMatch) {
              const h = parseInt(timeMatch[1])
              const m = parseInt(timeMatch[2])
              const mins = h * 60 + m
              
              // Morning shift: late after 8:15 (495 mins)
              // Afternoon shift: late after 2:15 PM (14:15 = 855 mins)
              if ((mins >= 495 && mins < 840) || mins >= 855) {
                aggregation[name].late += 1
              }
            }
          }
        }
      }

      const results = Object.entries(aggregation).map(([name, data]) => ({
        rysenovaName: name,
        present_days: data.present,
        absent_days: data.absent,
        late_days: data.late
      }))

      setParsedData(results)
      
      const matched = results.map(r => ({
        ...r,
        staff_id: findBestMatch(r.rysenovaName) || ''
      }))
      setMatchedRecords(matched)
      addToast('File parsed and aggregated', 'success')
    }
    reader.readAsText(file)
  }


  const handleDragOver = (e) => {
    e.preventDefault()
    setIsDragging(true)
  }

  const handleDragLeave = () => {
    setIsDragging(false)
  }

  const handleDrop = (e) => {
    e.preventDefault()
    setIsDragging(false)
    const file = e.dataTransfer.files[0]
    if (file) processFile(file)
  }

  const handleManualMatch = (index, staffId) => {
    const updated = [...matchedRecords]
    updated[index].staff_id = staffId
    setMatchedRecords(updated)
  }

  const handleImport = async () => {
    const unmatched = matchedRecords.some(r => !r.staff_id)
    if (unmatched) {
      if (!confirm('Some records are unmatched. They will be skipped. Continue?')) return
    }

    const recordsToImport = matchedRecords.filter(r => r.staff_id).map(r => ({
      staff_id: r.staff_id,
      present_days: r.present_days,
      absent_days: r.absent_days,
      late_days: r.late_days
    }))

    if (recordsToImport.length === 0) {
      addToast('No records to import', 'error')
      return
    }

    try {
      setLoading(true)
      const res = await fetch('/api/attendance/import', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ month, year, records: recordsToImport })
      })
      const data = await res.json()
      if (data.success) {
        addToast(`Successfully imported ${data.imported} records`, 'success')
        setParsedData([])
        setMatchedRecords([])
      } else {
        throw new Error(data.error)
      }
    } catch (err) {
      addToast(err.message || 'Import failed', 'error')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ background: '#F8FAFC', minHeight: '100vh', fontFamily: 'Inter, sans-serif' }}>
      <Navbar />
      <main style={{ maxWidth: '1000px', margin: '0 auto', padding: '32px 24px' }}>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '32px' }}>
          <button onClick={() => router.back()} style={{ background: 'white', border: '1px solid #E2E8F0', borderRadius: '8px', padding: '8px', cursor: 'pointer', color: '#64748B' }}>
            <ChevronLeft size={20} />
          </button>
          <div>
            <h1 style={{ fontSize: '24px', fontWeight: 800, color: '#0F172A', margin: 0 }}>Attendance Import</h1>
            <p style={{ color: '#64748B', fontSize: '14px', margin: '4px 0 0 0' }}>Upload Rysenova CSV to sync monthly attendance summary</p>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px', alignItems: 'start' }}>
          
          {/* Settings Card */}
          <div style={{ background: 'white', borderRadius: '16px', padding: '24px', border: '1px solid #E2E8F0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
            <h2 style={{ fontSize: '16px', fontWeight: 700, color: '#1E293B', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Calendar size={18} color="#3B82F6" />
              Import Settings
            </h2>
            
            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#64748B', marginBottom: '8px' }}>Select Month</label>
              <select 
                style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #E2E8F0', background: '#F8FAFC', outline: 'none' }}
                value={month}
                onChange={e => setMonth(parseInt(e.target.value))}
              >
                {months.map((m, i) => <option key={m} value={i + 1}>{m}</option>)}
              </select>
            </div>

            <div style={{ marginBottom: '32px' }}>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: 600, color: '#64748B', marginBottom: '8px' }}>Select Year</label>
              <input 
                type="number"
                style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #E2E8F0', background: '#F8FAFC', outline: 'none' }}
                value={year}
                onChange={e => setYear(parseInt(e.target.value))}
              />
            </div>

            <div 
              style={{ 
                border: isDragging ? '2px dashed #3B82F6' : '2px dashed #E2E8F0',
                background: isDragging ? '#EFF6FF' : '#F8FAFC',
                borderRadius: '12px',
                padding: '40px 20px',
                textAlign: 'center',
                cursor: 'pointer',
                transition: 'all 0.2s ease'
              }}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current.click()}
            >
              <Upload size={32} color={isDragging ? '#3B82F6' : '#94A3B8'} style={{ marginBottom: '12px' }} />
              <p style={{ fontSize: '14px', fontWeight: 600, color: '#1E293B', margin: '0 0 4px 0' }}>Drop CSV file here</p>
              <p style={{ fontSize: '12px', color: '#64748B', margin: 0 }}>or click to browse</p>
              <input 
                type="file" 
                ref={fileInputRef} 
                onChange={handleFileUpload} 
                accept=".csv" 
                style={{ display: 'none' }} 
              />
            </div>
          </div>

          {/* Preview Card */}
          <div style={{ background: 'white', borderRadius: '16px', padding: '24px', border: '1px solid #E2E8F0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)', minHeight: '400px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: '#1E293B', display: 'flex', alignItems: 'center', gap: '8px', margin: 0 }}>
                <FileText size={18} color="#3B82F6" />
                Data Preview
              </h2>
              {matchedRecords.length > 0 && (
                <button 
                  onClick={handleImport}
                  disabled={loading}
                  style={{ background: '#10B981', color: 'white', border: 'none', borderRadius: '8px', padding: '8px 16px', fontSize: '13px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}
                >
                  {loading ? 'Importing...' : <><Check size={16} /> Confirm Import</>}
                </button>
              )}
            </div>

            {matchedRecords.length === 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '300px', color: '#94A3B8' }}>
                <AlertCircle size={48} strokeWidth={1} style={{ marginBottom: '16px', opacity: 0.5 }} />
                <p style={{ fontSize: '14px' }}>Upload a Rysenova CSV to see preview</p>
              </div>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                  <thead>
                    <tr style={{ textAlign: 'left', borderBottom: '1px solid #F1F5F9' }}>
                      <th style={{ padding: '12px 8px', color: '#64748B', fontWeight: 600 }}>Rysenova Name</th>
                      <th style={{ padding: '12px 8px', color: '#64748B', fontWeight: 600 }}>Matched Staff</th>
                      <th style={{ padding: '12px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>Present</th>
                      <th style={{ padding: '12px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>Absent</th>
                      <th style={{ padding: '12px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>Late</th>
                      <th style={{ padding: '12px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {matchedRecords.map((record, idx) => (
                      <tr key={idx} style={{ borderBottom: '1px solid #F8FAFC' }}>
                        <td style={{ padding: '12px 8px', fontWeight: 600, color: '#334155' }}>{record.rysenovaName}</td>
                        <td style={{ padding: '12px 8px' }}>
                          <select 
                            style={{ 
                                padding: '6px', 
                                borderRadius: '6px', 
                                border: '1px solid #E2E8F0', 
                                width: '100%', 
                                fontSize: '12px',
                                background: record.staff_id ? '#F0FDF4' : '#FEF2F2',
                                borderColor: record.staff_id ? '#BBF7D0' : '#FECACA'
                            }}
                            value={record.staff_id}
                            onChange={(e) => handleManualMatch(idx, e.target.value)}
                          >
                            <option value="">-- Unmatched --</option>
                            {staff.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                          </select>
                        </td>
                        <td style={{ padding: '12px 8px', textAlign: 'center' }}>{record.present_days}</td>
                        <td style={{ padding: '12px 8px', textAlign: 'center' }}>{record.absent_days}</td>
                        <td style={{ padding: '12px 8px', textAlign: 'center' }}>{record.late_days}</td>
                        <td style={{ padding: '12px 8px', textAlign: 'center' }}>
                          {record.staff_id ? (
                            <span style={{ background: '#DCFCE7', color: '#15803D', padding: '2px 8px', borderRadius: '10px', fontSize: '11px', fontWeight: 700 }}>Matched</span>
                          ) : (
                            <span style={{ background: '#FEE2E2', color: '#B91C1C', padding: '2px 8px', borderRadius: '10px', fontSize: '11px', fontWeight: 700 }}>Unmatched</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}
