'use client'
import { useState, useEffect, useRef, Fragment } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '../../lib/supabase'
import Navbar from '../../components/Navbar'
import { useToast } from '../../components/Toast'
import { Upload, Check, AlertCircle, Trash2, ChevronLeft, Calendar, FileText, ChevronDown, ChevronUp } from 'lucide-react'

export default function AttendanceImportPage() {
  const router = useRouter()
  const { addToast } = useToast()
  const fileInputRef = useRef(null)

  const [month, setMonth] = useState(new Date().getMonth() + 1)
  const [year, setYear] = useState(new Date().getFullYear())
  const [loading, setLoading] = useState(false)
  const [staff, setStaff] = useState([])
  const [matchedRecords, setMatchedRecords] = useState([])
  const [isDragging, setIsDragging] = useState(false)
  const [importMode, setImportMode] = useState('summary') // 'summary' or 'daily'
  const [expandedRows, setExpandedRows] = useState({})

  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ]

  const nameAliases = {
    'shahdat': 'shahadat',
    'rabiul': 'robiul',
    'alam noor': 'alam nur',
    'esha': 'esa',
    'ajoy': 'ajoy',
    'sumon chef': 'sumon',
    'rafat islam': 'rafat',
    'hafizur islam': 'hafizur',
    'masum billah': 'masum'
  }

  useEffect(() => {
    const token = localStorage.getItem('cc_token')
    const role = localStorage.getItem('cc_role')
    if (!token || role !== 'admin') {
      router.replace('/')
      return
    }
    fetchStaff()
  }, [router])

  async function fetchStaff() {
    const { data } = await supabase.from('staff').select('id, name').eq('is_active', true).order('name')
    setStaff(data || [])
  }

  function normalizeName(name) {
    if (!name) return ''
    let n = name.toLowerCase().trim()
    for (const [key, val] of Object.entries(nameAliases)) {
      if (n.includes(key)) return val
    }
    return n
  }

  function findBestMatch(rysenovaName) {
    if (!rysenovaName) return null
    const normalized = normalizeName(rysenovaName)
    
    // Direct match
    let match = staff.find(s => normalizeName(s.name) === normalized)
    if (match) return match.id

    // Partial match
    match = staff.find(s => {
      const sName = normalizeName(s.name)
      return sName.includes(normalized) || normalized.includes(sName)
    })
    if (match) return match.id

    return null
  }

  const handleFileUpload = (e) => {
    const file = e.target.files[0]
    if (!file) return
    processFile(file)
  }

  const processFile = (file) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target.result
      const rows = text.split(/\r?\n/).map(row => {
        return row.split(',').map(cell => cell.replace(/^"(.*)"$/, '$1').trim())
      })

      if (importMode === 'summary') {
        processSummaryFormat(rows)
      } else {
        processDailyFormat(rows)
      }
    }
    reader.readAsText(file)
  }

  function processSummaryFormat(rows) {
    const header = rows[3] || []
    const nameIdx = header.findIndex(h => h.toLowerCase().includes('name') || h.toLowerCase().includes('employee'))
    const finalNameIdx = nameIdx !== -1 ? nameIdx : 0

    const dataRows = rows.slice(4)
    const aggregation = {}

    for (const row of dataRows) {
      if (row.length < 2) continue
      const name = row[finalNameIdx]
      if (!name || name === 'Generated by Rysenova' || name.toLowerCase().includes('employee') || name.toLowerCase().includes('total')) continue
      
      const col4 = row[4] || ''
      if (col4.toLowerCase().includes('day')) {
        aggregation[name] = {
          present: parseDays(row[4]),
          absent: parseDays(row[5]),
          late: 0
        }
      }
    }

    const results = Object.entries(aggregation).map(([name, data]) => ({
      rysenovaName: name,
      present_days: data.present,
      absent_days: data.absent,
      late_days: data.late,
      staff_id: findBestMatch(name) || ''
    }))

    setMatchedRecords(results)
    addToast('Summary file parsed', 'success')
  }

  function parseDays(val) {
    if (!val || val === '--') return 0
    const match = val.match(/^(\d+)/)
    return match ? parseInt(match[1]) : 0
  }

  function processDailyFormat(rows) {
    const header = rows[4] || []
    const dayColumns = header.slice(8).filter(h => h && /\d+/.test(h))
    
    const dataRows = rows.slice(5)
    const results = []

    for (const row of dataRows) {
      if (row.length < 9) continue
      const name = row[0]
      if (!name || name.toLowerCase().includes('employee') || name.toLowerCase().includes('total')) continue

      const dailyData = []
      let presentCount = 0
      let absentCount = 0
      let lateCount = 0

      dayColumns.forEach((h, i) => {
        const dayNum = parseInt(h.match(/\d+/)[0])
        const cell = row[8 + i] || ''
        
        if (cell === '-') return

        let status = 'present'
        let checkIn = null
        let checkOut = null

        if (cell === 'Absent') {
          status = 'absent'
          absentCount++
        } else {
          const timePart = cell.split('\n')[0]
          const times = timePart.split(' - ')
          checkIn = times[0]
          checkOut = times[1] === '--' ? null : times[1]

          const timeMatch = checkIn.match(/(\d+):(\d+)\s*(AM|PM)/i)
          if (timeMatch) {
            let hTime = parseInt(timeMatch[1])
            const mTime = parseInt(timeMatch[2])
            const ampm = timeMatch[3].toUpperCase()
            
            if (ampm === 'PM' && hTime < 12) hTime += 12
            if (ampm === 'AM' && hTime === 12) hTime = 0
            
            const mins = hTime * 60 + mTime

            if (hTime < 14) { // Morning
              if (mins > 495) { // 8:15 AM
                status = 'late'
                lateCount++
              } else {
                presentCount++
              }
            } else if (hTime < 19) { // Afternoon
              if (mins > 855) { // 2:15 PM
                status = 'late'
                lateCount++
              } else {
                presentCount++
              }
            } else { // Night
              status = 'present'
              presentCount++
            }
          } else {
            presentCount++
          }
        }

        dailyData.push({
          date: `${year}-${String(month).padStart(2, '0')}-${String(dayNum).padStart(2, '0')}`,
          status,
          check_in_time: checkIn,
          check_out_time: checkOut
        })
      })

      results.push({
        rysenovaName: name,
        present_days: presentCount,
        absent_days: absentCount,
        late_days: lateCount,
        staff_id: findBestMatch(name) || '',
        daily: dailyData
      })
    }

    setMatchedRecords(results)
    addToast('Daily file parsed', 'success')
  }

  const handleManualMatch = (index, staffId) => {
    const updated = [...matchedRecords]
    updated[index].staff_id = staffId
    setMatchedRecords(updated)
  }

  const toggleExpand = (idx) => {
    setExpandedRows(prev => ({ ...prev, [idx]: !prev[idx] }))
  }

  const handleImport = async () => {
    const unmatched = matchedRecords.some(r => !r.staff_id)
    if (unmatched) {
      if (!confirm('Some records are unmatched. They will be skipped. Continue?')) return
    }

    try {
      setLoading(true)
      
      if (importMode === 'daily') {
        const dailyRecords = []
        matchedRecords.forEach(r => {
          if (!r.staff_id) return
          r.daily.forEach(day => {
            dailyRecords.push({
              staff_id: r.staff_id,
              date: day.date,
              status: day.status,
              check_in_time: day.check_in_time,
              check_out_time: day.check_out_time,
              note: 'Imported from Rysenova'
            })
          })
        })

        if (dailyRecords.length > 0) {
          const { error } = await supabase.from('attendance').upsert(dailyRecords, { onConflict: 'staff_id,date' })
          if (error) throw error
        }
      }

      const summaryRecords = matchedRecords.filter(r => r.staff_id).map(r => ({
        staff_id: r.staff_id,
        month: parseInt(month),
        year: parseInt(year),
        present_days: r.present_days,
        absent_days: r.absent_days,
        late_days: r.late_days,
        source: 'rysenova',
        updated_at: new Date().toISOString()
      }))

      const { error: summaryError } = await supabase
        .from('monthly_attendance_summary')
        .upsert(summaryRecords, { onConflict: 'staff_id,month,year' })

      if (summaryError) throw summaryError

      addToast(`Successfully imported ${summaryRecords.length} records`, 'success')
      setMatchedRecords([])
    } catch (err) {
      addToast(err.message || 'Import failed', 'error')
    } finally {
      setLoading(false)
    }
  }

  const totalPresent = matchedRecords.reduce((s, r) => s + r.present_days, 0)
  const totalLate = matchedRecords.reduce((s, r) => s + r.late_days, 0)
  const totalAbsent = matchedRecords.reduce((s, r) => s + r.absent_days, 0)

  return (
    <div style={{ background: '#F8FAFC', minHeight: '100vh', fontFamily: 'Inter, sans-serif' }}>
      <Navbar />
      <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '32px 24px' }}>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '32px' }}>
          <button onClick={() => router.back()} style={{ background: 'white', border: '1px solid #E2E8F0', borderRadius: '8px', padding: '8px', cursor: 'pointer', color: '#64748B' }}>
            <ChevronLeft size={20} />
          </button>
          <div>
            <h1 style={{ fontSize: '24px', fontWeight: 800, color: '#0F172A', margin: 0 }}>Attendance Import</h1>
            <p style={{ color: '#64748B', fontSize: '14px', margin: '4px 0 0 0' }}>Upload Rysenova CSV to sync attendance data</p>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '8px', marginBottom: '24px' }}>
          <button 
            onClick={() => { setImportMode('summary'); setMatchedRecords([]); }}
            style={{
              padding: '8px 16px', borderRadius: '20px', border: '1px solid ' + (importMode === 'summary' ? '#3B82F6' : '#E2E8F0'),
              background: importMode === 'summary' ? '#3B82F6' : 'white', color: importMode === 'summary' ? 'white' : '#64748B',
              fontSize: '13px', fontWeight: 600, cursor: 'pointer'
            }}
          >
            Summary Import
          </button>
          <button 
            onClick={() => { setImportMode('daily'); setMatchedRecords([]); }}
            style={{
              padding: '8px 16px', borderRadius: '20px', border: '1px solid ' + (importMode === 'daily' ? '#3B82F6' : '#E2E8F0'),
              background: importMode === 'daily' ? '#3B82F6' : 'white', color: importMode === 'daily' ? 'white' : '#64748B',
              fontSize: '13px', fontWeight: 600, cursor: 'pointer'
            }}
          >
            Daily Import
          </button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: '24px', alignItems: 'start' }}>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
            <div style={{ background: 'white', borderRadius: '16px', padding: '24px', border: '1px solid #E2E8F0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: '#1E293B', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Calendar size={18} color="#3B82F6" />
                Import Settings
              </h2>
              
              <div style={{ marginBottom: '20px' }}>
                <label className="label">Select Month</label>
                <select 
                  className="input"
                  style={{ width: '100%' }}
                  value={month}
                  onChange={e => setMonth(parseInt(e.target.value))}
                >
                  {months.map((m, i) => <option key={m} value={i + 1}>{m}</option>)}
                </select>
              </div>

              <div style={{ marginBottom: '32px' }}>
                <label className="label">Select Year</label>
                <input 
                  type="number"
                  className="input"
                  style={{ width: '100%' }}
                  value={year}
                  onChange={e => setYear(parseInt(e.target.value))}
                />
              </div>

              <div 
                style={{ 
                  border: isDragging ? '2px dashed #3B82F6' : '2px dashed #E2E8F0',
                  background: isDragging ? '#EFF6FF' : '#F8FAFC',
                  borderRadius: '12px',
                  padding: '40px 20px',
                  textAlign: 'center',
                  cursor: 'pointer',
                  transition: 'all 0.2s ease'
                }}
                onDragOver={e => { e.preventDefault(); setIsDragging(true); }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={e => { e.preventDefault(); setIsDragging(false); const file = e.dataTransfer.files[0]; if (file) processFile(file); }}
                onClick={() => fileInputRef.current.click()}
              >
                <Upload size={32} color={isDragging ? '#3B82F6' : '#94A3B8'} style={{ marginBottom: '12px' }} />
                <p style={{ fontSize: '14px', fontWeight: 600, color: '#1E293B', margin: '0 0 4px 0' }}>Drop CSV file here</p>
                <p style={{ fontSize: '12px', color: '#64748B', margin: 0 }}>or click to browse</p>
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileUpload} 
                  accept=".csv" 
                  style={{ display: 'none' }} 
                />
              </div>
            </div>

            {matchedRecords.length > 0 && (
              <div style={{ background: '#3B82F6', borderRadius: '16px', padding: '24px', color: 'white', boxShadow: '0 10px 15px -3px rgba(59, 130, 246, 0.4)' }}>
                <h3 style={{ fontSize: '14px', fontWeight: 700, opacity: 0.8, textTransform: 'uppercase', marginBottom: '16px' }}>Parsed Summary</h3>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ opacity: 0.8 }}>Present</span>
                    <span style={{ fontWeight: 800 }}>{totalPresent}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ opacity: 0.8 }}>Late</span>
                    <span style={{ fontWeight: 800 }}>{totalLate}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ opacity: 0.8 }}>Absent</span>
                    <span style={{ fontWeight: 800 }}>{totalAbsent}</span>
                  </div>
                </div>
              </div>
            )}
          </div>

          <div style={{ background: 'white', borderRadius: '16px', padding: '24px', border: '1px solid #E2E8F0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)', minHeight: '600px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
              <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#1E293B', display: 'flex', alignItems: 'center', gap: '8px', margin: 0 }}>
                <FileText size={20} color="#3B82F6" />
                Data Preview
              </h2>
              {matchedRecords.length > 0 && (
                <button 
                  onClick={handleImport}
                  disabled={loading}
                  style={{ background: '#10B981', color: 'white', border: 'none', borderRadius: '8px', padding: '10px 20px', fontSize: '14px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px' }}
                >
                  {loading ? 'Processing...' : <><Check size={18} /> Confirm Import</>}
                </button>
              )}
            </div>

            {matchedRecords.length === 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '400px', color: '#94A3B8' }}>
                <AlertCircle size={64} strokeWidth={1} style={{ marginBottom: '16px', opacity: 0.5 }} />
                <p style={{ fontSize: '16px' }}>Upload a Rysenova CSV to see preview</p>
                <p style={{ fontSize: '13px', marginTop: '8px' }}>Format: {importMode.toUpperCase()}</p>
              </div>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                  <thead>
                    <tr style={{ textAlign: 'left', borderBottom: '1px solid #F1F5F9' }}>
                      <th style={{ padding: '16px 8px', color: '#64748B', fontWeight: 600 }}>Rysenova Name</th>
                      <th style={{ padding: '16px 8px', color: '#64748B', fontWeight: 600 }}>Matched Staff</th>
                      <th style={{ padding: '16px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>P</th>
                      <th style={{ padding: '16px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>L</th>
                      <th style={{ padding: '16px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>A</th>
                      <th style={{ padding: '16px 8px', color: '#64748B', fontWeight: 600, textAlign: 'center' }}>Status</th>
                      {importMode === 'daily' && <th style={{ padding: '16px 8px' }}></th>}
                    </tr>
                  </thead>
                  <tbody>
                    {matchedRecords.map((record, idx) => (
                      <Fragment key={idx}>
                        <tr style={{ borderBottom: '1px solid #F8FAFC', background: expandedRows[idx] ? '#F1F5F9' : 'transparent' }}>
                          <td style={{ padding: '16px 8px', fontWeight: 700, color: '#334155' }}>{record.rysenovaName}</td>
                          <td style={{ padding: '16px 8px' }}>
                            <select 
                              className="input"
                              style={{ 
                                  padding: '6px', 
                                  fontSize: '12px',
                                  background: record.staff_id ? '#F0FDF4' : '#FEF2F2',
                                  borderColor: record.staff_id ? '#BBF7D0' : '#FECACA'
                              }}
                              value={record.staff_id}
                              onChange={(e) => handleManualMatch(idx, e.target.value)}
                            >
                              <option value="">-- Unmatched --</option>
                              {staff.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                            </select>
                          </td>
                          <td style={{ padding: '16px 8px', textAlign: 'center', color: '#10B981', fontWeight: 700 }}>{record.present_days}</td>
                          <td style={{ padding: '16px 8px', textAlign: 'center', color: '#EF4444', fontWeight: 700 }}>{record.late_days}</td>
                          <td style={{ padding: '16px 8px', textAlign: 'center', color: '#64748B', fontWeight: 700 }}>{record.absent_days}</td>
                          <td style={{ padding: '16px 8px', textAlign: 'center' }}>
                            {record.staff_id ? (
                              <span style={{ background: '#DCFCE7', color: '#15803D', padding: '4px 10px', borderRadius: '12px', fontSize: '11px', fontWeight: 700 }}>MATCHED</span>
                            ) : (
                              <span style={{ background: '#FEE2E2', color: '#B91C1C', padding: '4px 10px', borderRadius: '12px', fontSize: '11px', fontWeight: 700 }}>MISSING</span>
                            )}
                          </td>
                          {importMode === 'daily' && (
                            <td style={{ padding: '16px 8px' }}>
                              <button 
                                onClick={() => toggleExpand(idx)}
                                style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#64748B' }}
                              >
                                {expandedRows[idx] ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                              </button>
                            </td>
                          )}
                        </tr>
                        {expandedRows[idx] && record.daily && (
                          <tr>
                            <td colSpan={7} style={{ padding: '0 0 16px 0' }}>
                              <div style={{ background: '#F8FAFC', margin: '0 8px', borderRadius: '12px', padding: '16px', border: '1px solid #E2E8F0' }}>
                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '8px' }}>
                                  {record.daily.map((day, dIdx) => (
                                    <div key={dIdx} style={{ background: 'white', padding: '8px 12px', borderRadius: '8px', border: '1px solid #F1F5F9', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                      <div>
                                        <p style={{ fontSize: '11px', fontWeight: 700, color: '#64748B', margin: 0 }}>Day {day.date.split('-')[2]}</p>
                                        <p style={{ fontSize: '12px', fontWeight: 600, color: day.status === 'late' ? '#EF4444' : day.status === 'absent' ? '#64748B' : '#10B981', margin: 0 }}>
                                          {day.check_in_time || day.status.toUpperCase()}
                                        </p>
                                      </div>
                                      {day.check_out_time && (
                                        <p style={{ fontSize: '11px', color: '#94A3B8', margin: 0 }}>to {day.check_out_time}</p>
                                      )}
                                    </div>
                                  ))}
                                </div>
                              </div>
                            </td>
                          </tr>
                        )}
                      </Fragment>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}
